### ISSUE TITLE
mips/mipsel: overflow of int

### ISSUE THREAD

**Issue by powersj** [microsoft/go-mssqldb#123]
**Describe the bug**

Similar to #53, during a cross-build on mips and mipsel the following failure occurs:

```
/go/pkg/mod/github.com/microsoft/go-mssqldb@v1.3.0/ucs22str.go:23:20: 0xFFFFFFF8 (untyped int constant 4294967288) overflows int
```

**To Reproduce**

Import the library and cross-build for mips and mipsel 

**Expected behavior**

Successfully build

**Comment by shueybubbles** [comment]
the build matrix is rather complex to detect breaks.
Should we build and release github.com/microsoft/go-sqlcmd on mips/mipsel too?

**Comment by powersj** [comment]
For some background as to how I ran across this: I discovered this when converting Telegraf, which supports a large number of architectures, from the original https://github.com/denisenkom/go-mssqldb project to this fork.
