### ISSUE TITLE
..\pkg\mod\github.com\microsoft\go-mssqldb@v0.15.0\tds.go:489:20: 0xFFFFFFF8 (untyped int constant 4294967288) overflows int  

### ISSUE THREAD

**Issue by anshul7248** [microsoft/go-mssqldb#135]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by shueybubbles** [comment]
Please try a newer version and provide steps to reproduce the problem.
