### ISSUE TITLE
connection fails when using specific connection string with specific password

### ISSUE THREAD

**Issue by LeandroFranciscato** [microsoft/go-mssqldb#147]
**Describe the bug**
Got a connection error (below) when trying to connect using a specific connection string format with a specific password.
Other connection string format work well, it only fails in a specific format. 

IMPORTANT: 
The password follows the [SQL SERVER password policy:](https://learn.microsoft.com/en-us/sql/relational-databases/security/password-policy)

connection failing:
![image](https://github.com/microsoft/go-mssqldb/assets/6653867/19725722-0219-4478-ba40-334322ef4006)

connection working fine, with a different connection string format:
![image](https://github.com/microsoft/go-mssqldb/assets/6653867/887c76e6-122f-4838-b90f-3c4b680096dd)

other connection working fine with a third connection string format:
![image](https://github.com/microsoft/go-mssqldb/assets/6653867/1914d274-c867-4a9c-aae3-1e73419c438b)

```
Exception message: `mssql: login error: Login failed for user 'SA'.`
Stack trace: 
```

**To Reproduce**

docker command to run a local DB in linux:

```bash
docker run -e "ACCEPT_EULA=Y" \
  -e "MSSQL_SA_PASSWORD=pwd" \
  -p 1433:1433 --name sql1 --hostname sql1 \
  -d mcr.microsoft.com/mssql/server:2022-latest
```

`main.go` file with the connection:

```go
package main

import (
	"context"
	"database/sql"
	"fmt"

	"github.com/microsoft/go-mssqldb/azuread"
)

func main() {
	mssqlHost := "localhost"
	mssqlUser := "SA"
	mssqlPassword := "pwd"
	//connectionString := fmt.Sprintf("server=%s;user id=%s;password=%s;port=1433;", mssqlHost, mssqlUser, mssqlPassword)
	connectionString := fmt.Sprintf(`sqlserver://%s@%s?&password=%s`, mssqlUser, mssqlHost, mssqlPassword)
	//connectionString := fmt.Sprintf(`sqlserver://%s:%s@%s`, mssqlUser, mssqlPassword, mssqlHost)

	db, err := sql.Open(azuread.DriverName, connectionString)
	if err != nil {
		panic(err)
	}

	conn, err := db.Conn(context.Background())
	if err != nil {
		panic(err)
	}

	fmt.Println("connected")

	err = conn.Close()
	if err != nil {
		panic(err)
	}

}
```

**Expected behavior**
The connection should work!

### Further technical details
SQL Server version: SQL Server 2022
Operating system: Ubuntu 20.04 LTS
Table schema: 

**Additional context**
Nothing else to mention

**Comment by magnonta** [comment]
Facing the same issue here. Thanks for opening this.

**Comment by lg-oainger** [comment]
+1 on this

**Comment by shueybubbles** [comment]
The working URL format with the `:` is what is listed in the [README](https://github.com/microsoft/go-mssqldb#the-connection-string-can-be-specified-in-one-of-three-formats).
Per the readme, `username and password appears before the host` for URLs. 
If I've misread your code, please point out which specific format the readme lists as valid that isn't working.
thx

**Comment by LeandroFranciscato** [comment]
I got your point and it makes sense.
However, the format I was using was working fine for some password and for other not, I found it strange and decided to open the issue. 
Anyways, thank you for answering and pointing the way.

**Comment by shueybubbles** [comment]
I don't know the origin of the format and would be willing to support something different if there's enough demand.
One recommendation I have - if your app isn't using Entra ID (AAD auth), don't reference the `azuread` package at all. It drags in a bunch of dependencies you don't need for SQL auth or Windows auth.

**Comment by LeandroFranciscato** [comment]
Good tip, I'll check that.
Thanks.
