### ISSUE TITLE
can i use always encrypted with secure enclaves?

### ISSUE THREAD

**Issue by lifecycle67** [microsoft/go-mssqldb#162]
can i use always encrypted with secure enclaves?
not found doc about enclaves.

my environment is
- sql server 2019
- master key stored in key vault

when querying a simple SELECT SQL statement with the LIKE operator, an error message 33546 is returned.
It was fine in SSMS and C# code.

thanks.

**Comment by shueybubbles** [comment]
no, enclave support isn't available yet.
