### ISSUE TITLE
How can I send a list in the select query with IN?

### ISSUE THREAD

**Issue by bakbuz** [microsoft/go-mssqldb#183]
How can I send a list in the select query with **'IN'**?

For example:

```
var ids []uuid.UUID = ...

const query = "SELECT * FROM Products WHERE Id IN (@Ids) AND Deleted=0"

rows, err := repo.db.QueryContext(ctx, query,
  sql.Named("Ids", ids),
)
if err != nil {
return nil, err
}
defer rows.Close()
```

Best regards.

**Comment by shueybubbles** [comment]
SQL doesn't have a way to pass arrays at the protocol level.
Even .Net doesn't have a way to do it per https://stackoverflow.com/questions/2377506/pass-array-parameter-in-sqlcommand

**Comment by bakbuz** [comment]
Thanks
