### ISSUE TITLE
cannot connect to MSSQLSERVER on localhost: "No connection could be made because the target machine actively refused it"

### ISSUE THREAD

**Issue by param-modulation** [microsoft/go-mssqldb#189]
**Problem**
I call `sql.Open("sqlserver", connStr)`.  I then call `db.Ping()` to see whether I have successfully connected.  Regardless of the variations of connections strings I've tried, I cannot successfully connect + query the DB.

**Environment**
- Windows 10 Pro
- client code written in Go, running (via _dlv_ debugger)__ in Visual Studio Code
- Microsoft SQL Server Developer (64-bit), Version 16.0.1115.1
- Windows firewall inbound rule permits connections to port 1433
![image](https://github.com/microsoft/go-mssqldb/assets/167443929/e9088784-34b0-4c79-a46a-56d0886e07a6)
![image](https://github.com/microsoft/go-mssqldb/assets/167443929/429d627c-c9cb-49e6-91de-4d3de9fdb701)
![image](https://github.com/microsoft/go-mssqldb/assets/167443929/6605200e-e980-4245-a3e3-3e5af41d333d)

**What I've Tried**
- Authenticating as same user via Microsoft SQL Server Management Studio (works, but requires "Additional Connection Parameters" `Integrated Security=False` to prevent SQL Server's preference for ignoring the supplied username and instead using current Windows user + Windows Auth.)
- authenticating + querying DB via _sqlcmd_ in terminal (works: sqlcmd -S localhost -U itsme -P foobar)
- looking in Event Viewer for 4661 + 4656 logs (zero found)
- looking in MSMS > Management > SQL Server Logs > Current (no indications of a failed auth.)

**Code Snippet**
	// query := url.Values{}
	// // query.Add("Server", "localhost")
	// query.Add("Database", "master")
	// query.Add("Encrypt", "disable")
	// query.Add("Trusted_Connection", "True")
	// query.Add("Integrated Security", "False")

	//connStr := "sqlserver://itsme:foobar@localhost:1433?database=master&Trusted_Connection=True&Integrated+Security=False"

	connStr := fmt.Sprintf("server=%s;user id=%s;password=%s;port=%s", "localhost", "itsme", "foobar", "1433")

	//connStr := "server=127.0.0.1;user id=itsme;password=foobar;database=master"

	// u := &url.URL{
	// 	Scheme:   "sqlserver",
	// 	User:     url.UserPassword("itsme", "foobar"),
	// 	Host:     fmt.Sprintf("%s:%d", "127.0.0.1", 1433),
	// 	RawQuery: query.Encode(),
	// }

	slog.Info(connStr)

	db, err := sql.Open("sqlserver", connStr)

	if err != nil && db != nil {
		slog.Error("error opening DB connection: %w", err)
                return nil
	}

	err = db.Ping()
	if err != nil {
		slog.Error("failed to open connection to SQL Server", "err", err)
		return nil
	}

**Expected**
One of the attempted connection strings should allow me to connect + then ping the DB.

**Actual**
I always see "ERROR Failed to open connection to SQL Server err="unable to open tcp connection with host 'localhost:1433': dial tcp [::1]:1433: connectex: No connection could be made because the target machine actively refused it.""

**Comment by 107295472** [comment]
SQL Server Browser service opens

**Comment by param-modulation** [comment]
SQL Server Browser service was not running, but starting it did not solve the problem.  (Thanks for the idea nonetheless!)

**Comment by param-modulation** [comment]
I got this working by doing the following:

1. windows-R > run menu > SQLServerManager16.msc
2. navigate to SQL Server Network Config > Protocols for MSSQLSERVER
3. right-mouse-button on tcp-ip, and enable it (mine was "disabled")
4. right-mouse-button again on tcp-ip > properties > IP addresses tab > scroll down to find the IP of interest (for me it was 127.0.0.1 and enable it)

Takeaways: despite being able to connect from command line and via MSSM UI, the server itself was not listening on an TCP-IP ports (as the error correctly said).

**Comment by shueybubbles** [comment]
sqlcmd uses named pipe and shared memory protocols in addition to tcp. Your app can use them too by including the appropriate packages.

**Comment by 107295472** [comment]
I can connect using gorm, and his driver also uses this.

**Comment by dlevy-msft** [comment]
> I can connect using gorm, and his driver also uses this.

Do you get the same error message when you don't include the port number?
