### ISSUE TITLE
BulkImport no longer supports Nullable types

### ISSUE THREAD

**Issue by vecknishwaran** [microsoft/go-mssqldb#190]
**Describe the bug**
Since upgrading from v1.7.0 to v1.7.1, the `bulkimport` function no longer supports nullable types. I receive the following error when attempting to import:

```
bulkcopy: mssql: invalid type for float column: sql.NullFloat64{%!s(float64=0) %!s(bool=true)}
```

I believe this issue was introduced following the changes made in pull request #179. I am willing to create a PR to address and fix this issue if needed.

**Comment by shueybubbles** [comment]
thx for opening an issue! A PR would be great. I suppose it means we're missing this test case? https://github.com/microsoft/go-mssqldb/blob/ada30cbaf031d81144e5c5487ddefd4f3dac0ef5/bulkcopy_test.go#L17
