### ISSUE TITLE
Connect using user-assigned identity via `ActiveDirectoryMSI`

### ISSUE THREAD

**Issue by alex-kuck** [microsoft/go-mssqldb#222]
**Describe the bug**
From the README it seems like the attached code should successfully authenticate to AzureSQL via Managed Identity. However, the request fails with the attached error.

```
Exception message: 

GET http://169.254.169.254/metadata/identity/oauth2/token
--------------------------------------------------------------------------------
RESPONSE 400 Bad Request
--------------------------------------------------------------------------------
{
  "error": "invalid_request",
  "error_description": "Identity not found"
}
--------------------------------------------------------------------------------
To troubleshoot, visit https://aka.ms/azsdk/go/identity/troubleshoot#managed-id

Stack trace: N/A
```
<img width="1468" alt="Screenshot 2024-10-02 at 09 38 50" src="https://github.com/user-attachments/assets/f6108385-ab07-45c4-bc82-1d21c187b986">

**To Reproduce**
```go
package db

import (
	"context"
	"database/sql"
	"fmt"
	"github.com/Azure/azure-sdk-for-go/sdk/azcore/policy"
	"github.com/Azure/azure-sdk-for-go/sdk/azidentity"
	mssql "github.com/microsoft/go-mssqldb"
	azureAd "github.com/microsoft/go-mssqldb/azuread"
)

func NewAzureSql(connection string) (db *sql.DB, err error) {  // connection: server=azuresql.database.windows.net;database=some-db;fedauth=ActiveDirectoryMSI;user id=XXX-YYY-ZZZZ;
	db, err = sql.Open(azureAd.DriverName, connection)
	return
        
         // The following works however
	//cred, err := azidentity.NewDefaultAzureCredential(nil)
	//if err != nil {
	//	err = fmt.Errorf("could not create default azure credential: %w", err)
	//	return
	//}
	//tokenProvider := func() (string, error) {
	//	token, err := cred.GetToken(context.TODO(), policy.TokenRequestOptions{
	//		Scopes: []string{"https://database.windows.net//.default"},
	//	})
	//	return token.Token, err
	//}
	//
	//connector, err := mssql.NewAccessTokenConnector(connection, tokenProvider)
	//if err != nil {
	//	err = fmt.Errorf("could not create access token connector: %w", err)
	//	return
	//}
	//
	//return sql.OpenDB(connector), err
}

```

**Expected behavior**
Ideally - and as the README suggests 😅  - the "simple" solution should work without having to provide a token provider manually.

### Further technical details
SQL Server version: Azure SQL (General Purpose - Serverless: Standard-series (Gen5), 2 vCores)
Operating system: Docker container running on AKS
Table schema

**Additional context**
Versions:

```go
github.com/microsoft/go-mssqldb v1.7.2
github.com/Azure/azure-sdk-for-go/sdk/azcore v1.9.1 // indirect
github.com/Azure/azure-sdk-for-go/sdk/azidentity v1.5.1 // indirect
github.com/Azure/azure-sdk-for-go/sdk/internal v1.5.1 // indirect
```

**Comment by shueybubbles** [comment]
the failed code example is using a user-assigned managed identity, while the succeeding example is using a system-assigned managed identity, afaict. Am I missing something?

**Comment by shueybubbles** [comment]
you could also use default authentication in the connection string instead of MSI, if default auth is known to work.

**Comment by alex-kuck** [comment]
Hi @shueybubbles , thanks for the quick reply! I just tried `ActiveDirectoryDefault` instead and it works like a charm! 😅 
We were using user-assigned identities in both cases, if I'm not mistaken 🤔 
We are using the same kind of (user-assigned) identities for Spring Boot applications as well. There it's working fine with JDBC connection via `authentication=ActiveDirectoryMSI;msiClientId=XXX-YYY-ZZZ;`, so I assumed the same mechanism should be used here as well 😅

**Comment by shueybubbles** [comment]
Did you query `suser_sname()` to verify you connected with the right account?

**Comment by alex-kuck** [comment]
I just checked, `suser_sname()` returns `nil`, but checking for `CURRENT_USER` returns the expected user assigned identity name.
