### ISSUE TITLE
Prelogin and login7 messages are missing some fields, leading to connection failures against certain endpoints

### ISSUE THREAD

**Issue by raymondb1** [microsoft/go-mssqldb#226]
The connection id / activity id / sequence number should be populated with valid values and semantics similar to what the other drivers (OLEDB, ODBC / SqlClient(s)).

Those are very important for traceability and debugging purposes (they allow correlation between what a client might see and execution server side).

Also the client id and PID of the login 7 message should be populated - the spec defines them as:

- ClientID: The unique client ID (created by using the NIC address). ClientID is the MAC address of the physical network layer. It is used to identify the client that is connecting to the server. 
- ClientPID: The process ID of the client application.

**Comment by shueybubbles** [comment]
@raymondb1  do you have any suggestions to help the sling folks on this related issue? https://github.com/microsoft/go-mssqldb/issues/230 ? Even with the connection id and trace id in prelogin, their second connection attempt gets disconnected.
