### ISSUE TITLE
ActiveDirectoryServicePrincipal connection string

### ISSUE THREAD

**Issue by RudraNirvan** [microsoft/go-mssqldb#23]
The [current set of examples](https://github.com/denisenkom/go-mssqldb/tree/master/examples) demonstrate how to connect using only two methods:

[simple](https://github.com/denisenkom/go-mssqldb/blob/master/examples/simple/simple.go): login/password
[MSI token](https://github.com/denisenkom/go-mssqldb/tree/master/examples/azuread-accesstoken)
How does one connect via the Service Principal of an application? I tried the following (and some variations of it) but it did not work:

"server=%s;user id=%s;password=%s;port=%d;database=%s;fedauth=ActiveDirectoryServicePrincipal;"
Shows this error: login error: Login failed for user <REDACTED>

--------------------------------------------------------------------------
Issue cloned from https://github.com/denisenkom/go-mssqldb/issues/749

**Comment by shueybubbles** [comment]
Is this issue saying that the code in your proposed example doesn't work?

**Comment by RudraNirvan** [comment]
@shueybubbles it actually does work, I was passing the parameters incorrectly. Therefore, created that PR to demonstrate a working example in case someone else wants to try "ActiveDirectoryServicePrincipal".

On that note, since you've renamed all the modules for this fork, I'll fork your fork and create new PRs.
