### ISSUE TITLE
Go version 1.18 TLS 1.0 and 1.1 disabled by default client-side (sql server old TLS versions not work)

### ISSUE THREAD

**Issue by fumin** [microsoft/go-mssqldb#33]
**Is your feature request related to a problem? Please describe.**
Yes, for the full discussion, see

https://github.com/denisenkom/go-mssqldb/issues/726

In short, there are a lot of smelly, shitty, shoddy MICROSOFT Sql Servers out there, that are stuck in TLS 1.0, which is deprecated by Go.

This results in the error:

```
* TLS Handshake failed: tls: server selected unsupported protocol version 301
```

**Describe the solution you'd like**
The fix is to allow users of this library to specify the minimum accepted TLS version as described in

https://github.com/denisenkom/go-mssqldb/issues/726#issuecomment-1098652011

**Describe alternatives you've considered**
None, the above solution is *the* solution, as there's no way to convince morons running MS SQLServer to upgrade their database.

**Additional context**
[Add any other context or screenshots about the feature request here.]

https://github.com/denisenkom/go-mssqldb/issues/726 was reported in March, and yet we are here in June with no progress.
Microsoft product managers, please, clean up this mess, *fast*.

**Comment by shueybubbles** [comment]
I invited the contributor of the other PR to port it here

**Comment by derwitzer** [comment]
@shueybubbles ist this bug fixed in the Microsoft fork of the MSSQL drivers?

**Comment by shueybubbles** [comment]
not yet, I hope to get to it soon.

**Comment by efjoubert** [comment]
Just change the  code at the beginning in SetupTLS to

config := tls.Config{
		ServerName:         hostInCertificate,
		InsecureSkipVerify: insecureSkipVerify,

		// fix for https://github.com/microsoft/go-mssqldb/issues/166
		// Go implementation of TLS payload size heuristic algorithm splits single TDS package to multiple TCP segments,
		// while SQL Server seems to expect one TCP segment per encrypted TDS package.
		// Setting DynamicRecordSizingDisabled to true disables that algorithm and uses 16384 bytes per TLS package
		DynamicRecordSizingDisabled: true,
		MinVersion:                  tls.VersionTLS10, //this is added
	}

That is all that is needed to solve the issue
