### ISSUE TITLE
unable to open tcp connection with host

### ISSUE THREAD

**Issue by hajsf** [microsoft/go-mssqldb#38]
I goth the below error:

```bash
2022/07/18 10:15:38 Prepare failed:unable to open tcp connection with host 'my-server:1433': dial tcp 172.16.20.185:1433: connectex: No connection could be made because the target machine actively refused it.
```
Though that I did the following:
1. Installed fresh version of MSSQL dev, first time MSSQL is installed at this machine, and confirmed it is running using `sqlcm`

<img width="368" alt="image" src="https://user-images.githubusercontent.com/98168280/179464794-91883009-c837-4a43-9bc7-aec78027bbbc.png">

2. Installed MSSQL studio (I'm to confirm MSSQLSERVER) is connected

<img width="490" alt="image" src="https://user-images.githubusercontent.com/98168280/179462391-39cd7e20-bf4c-48e6-a97e-1206ce97350a.png">

3. At Windows definder firewall, I allowed the connection of port `1433`

<img width="982" alt="image" src="https://user-images.githubusercontent.com/98168280/179461599-54b58c34-9c9a-4d60-ab9b-3f111e2170d9.png">

4. At `SQL server network connection -> protocols for MSSQLSERVER` I enabled both `Named Pipes` and `TCP/IP`

<img width="446" alt="image" src="https://user-images.githubusercontent.com/98168280/179461806-db1762ee-fe82-4bfc-9059-cc4f1a647051.png">

The code I'm trying to test is the simple one provided in the examples:
```go
package main

import (
	"database/sql"
	"flag"
	"fmt"
	"log"

	_ "github.com/microsoft/go-mssqldb"
)

var (
	debug         = flag.Bool("debug", false, "enable debugging")
	password      = flag.String("password", "", "the database password")
	port     *int = flag.Int("port", 1433, "the database port")
	server        = flag.String("server", "my-server", "the database server") 
	user          = flag.String("user", "sa", "the database user")                  
)

func main() {
	flag.Parse()

	if *debug {
		fmt.Printf(" password:%s\n", *password)
		fmt.Printf(" port:%d\n", *port)
		fmt.Printf(" server:%s\n", *server)
		fmt.Printf(" user:%s\n", *user)
	}

	connString := fmt.Sprintf("server=%s;user id=%s;password=%s;port=%d", *server, *user, *password, *port)
	if *debug {
		fmt.Printf(" connString:%s\n", connString)
	}
	conn, err := sql.Open("mssql", connString)
	if err != nil {
		log.Fatal("Open connection failed:", err.Error())
	}
	defer conn.Close()

	stmt, err := conn.Prepare("select 1, 'abc'")
	if err != nil {
		log.Fatal("Prepare failed:", err.Error())
	}
	defer stmt.Close()

	row := stmt.QueryRow()
	var somenumber int64
	var somechars string
	err = row.Scan(&somenumber, &somechars)
	if err != nil {
		log.Fatal("Scan failed:", err.Error())
	}
	fmt.Printf("somenumber:%d\n", somenumber)
	fmt.Printf("somechars:%s\n", somechars)

	fmt.Printf("bye\n")
}
```

**Comment by shueybubbles** [comment]
I didn't think you could put a URL in "Program" for the firewall setting. Most people put the path to sqlservr.exe there. 
Are you sure SSMS is using a tcp connection? Try forcing SSMS to use tcp by prefixing the server name with "tcp:" in the connection dialog.

**Comment by hajsf** [comment]
> Try forcing SSMS to use tcp by prefixing the server name with "tcp:" in the connection dialog.

It did not connect:

<img width="458" alt="image" src="https://user-images.githubusercontent.com/98168280/179546598-99df97b5-243e-4918-9fb8-95468841d421.png">

Also I added the `sqlserver.exe` to the firewall setting, but nothing changed:

<img width="785" alt="image" src="https://user-images.githubusercontent.com/98168280/179546870-12bf1a58-83a4-4f30-81b0-c180402011e0.png">

**Comment by hajsf** [comment]
> This would be some issue with your setup

Kindly see this, other people having same issue: https://stackoverflow.com/a/73032806/2441637

**Comment by hajsf** [comment]
Thanks, today I restarted my laptop and things working smoothly, not sure if I was missing restart after some process or if it is something else. it is fine with me now.

<img width="669" alt="image" src="https://user-images.githubusercontent.com/98168280/180642461-858cd830-1352-49cb-8124-57ce5afb6772.png">
