### ISSUE TITLE
IPV6 address support

### ISSUE THREAD

**Issue by shueybubbles** [microsoft/go-mssqldb#42]
**Describe the bug**
For some reason my VPN wouldn't resolve an IPv4 address for my server, just IPv6, and the test for `TestConnectViaIp` fails.

**To Reproduce**
Run the `TestConnectViaIp` with an ipv6-only network.
```
--- FAIL: TestConnectViaIp (0.00s)
    tds_test.go:341: Scan failed: parse "sqlserver://:@2001:4898:e0:bd:c525:913b:52f3:9a8a?disableRetry=false&log=127": invalid port ":9a8a" after host
2022/07/26 09:05:29 [{Hello} {World} {TVP}]
```

**Comment by PeterFeicht** [comment]
This is a problem with the test, or rather with [`msdsn.Config.URL`](https://github.com/microsoft/go-mssqldb/blob/9f3df54fcab6fb772d311cabc6caca386e826a87/msdsn/conn_str.go#L338). IPv6 addresses in URLs need to be enclosed in square brackets ([RFC 2732](https://www.rfc-editor.org/rfc/rfc2732)). However, `msdsn.Config.URL` doesn't handle that case and sets the host to the non-enclosed IPv6 address, which results in an invalid URL.

I think `msdsn.Parse` might also have a problem with IPv6 in URL DSNs (properly enclosed, that is). It would set the enclosed IP as the `Config.Host`, which might then fail during the connection, depending on whether [`net.LookupIP`](https://github.com/microsoft/go-mssqldb/blob/9f3df54fcab6fb772d311cabc6caca386e826a87/tds.go#L847) handles bracket-enclosed IPv6 addresses (`net.ParseIP` does not).

**Comment by r-stepanenko** [comment]
put [ ] around ip
