### ISSUE TITLE
can not build c-shared in andriod arm

### ISSUE THREAD

**Issue by labulakalia** [microsoft/go-mssqldb#53]
**Describe the bug**

If you are seeing an exception, include the full exceptions details (message and stack trace).

```
CGO_ENABLED=1 GOOS=android GOARCH=arm CC=/Users/xxx/sdk/andriod/ndk/25.1.8937393/toolchains/llvm/prebuilt/darwin-x86_64/bin/armv7a-linux-androideabi21-clang go build -buildmode=c-shared -o build/andriod/armeabi-v7a/aaa.so main.go
# github.com/microsoft/go-mssqldb
../../../go/pkg/mod/github.com/microsoft/go-mssqldb@v0.16.0/ucs22str.go:23:18: constant 4294967288 overflows int

```

**To Reproduce**
Include a complete code listing that we can run to reproduce the issue.

Partial code listings, or multiple fragments of code, will slow down our response or cause us to push the issue back to you to provide code to reproduce the issue.

**Expected behavior**

### Further technical details
SQL Server version: (e.g. SQL Server 2017)
Operating system: (e.g. Windows 2019, Ubuntu 18.04, macOS 10.13, Docker container)
Table schema

**Additional context**

**Comment by shueybubbles** [comment]
this commit should fix it. 
https://github.com/microsoft/go-mssqldb/commit/574b5281477cacf2861ba235bb753dee533ccdd5

I was going to wait until the kerberos PR is done before pushing a new version tag.

**Comment by labulakalia** [comment]
@shueybubbles thanks
