### ISSUE TITLE
Add named pipes support

### ISSUE THREAD

**Issue by shueybubbles** [microsoft/go-mssqldb#60]
Similar to the .Net SqlClient behavior:
1. Automatically infer named pipe connection from the `np:` prefix on the server name or from a name formatted as a UNC path like `\\servername\pipe\sql\query`
2. Allow packages to register a Dialer instance associated with a protocol. EG the core package will register a `tcp:` dialer and a new `namedpipe` package will register a `np:` dialer during `init()`
4. Enable the app to specify a global setting that is the order of which dialers to try when there is no prefix on the server name. The default will be tcp only.

**Comment by shueybubbles** [comment]
4. the connection timeout is cumulative for all dialers

**Comment by shueybubbles** [comment]
Fixed by #61

**Comment by Etran-H** [comment]
I want to use this, can you add a tag?
