### ISSUE TITLE
Kerberos on MacOS

### ISSUE THREAD

**Issue by DinkoMiljak** [microsoft/go-mssqldb#62]
Hi

After installing newest version of go-mssqldb repository (from 2022-10-26 - with 3 latest kerberos update) I tried to connect to sql server via kerberos (kbr5 provider) on Mac OS Monterey. 
I tried all kind of connect string, and the best I got is error provider krb5 not found.
My Azure Data Studio connection operating correctly (via /etc/krb5.conf), but golang application is unable to connect.

What I tried so far.

`authenticator=krb5;server=db.address.local;database=DWH;user id=myusername;password=mypassword;realm=address.local;krb5conffile=/etc/krb5.conf;`

`authenticator=krb5;server=db.address.local;database=DWH;user id=myusername;realm=domain.com;krb5conffile=/etc/krb5.conf;keytabfile=~/MyUserName.keytab
`

`authenticator=krb5;server=db.address.local;port=1433;krb5conffile=/etc/krb5.conf;krbcache=/tmp/krb5cc_1000
`

If I try to remove authenticator then I got user message user=. not found, etc...

What I'm missing?

**Comment by DinkoMiljak** [comment]
After the battle I was able to connect. This is my path:

KERBEROS
To use kerberos security on golang MAC application you need to run kinit with cache file

`kinit -c /tmp/SomeNameCachedCreds`

(To call kinit or klist you need to create /etc/krb5.conf which is not part of this text)

This will create cache file at specified location, which then can be used in connection string
Connect string version which use Cache file. Both version of connect string are correct

`authenticator=krb5;server=somedbserver;port=1433;user=someuser;krb5conffile=/etc/krb5.conf;krbcache=/tmp/SomeNameCachedCreds"`
`authenticator=krb5;server=somedbserver;port=1433;user=SOMEDOMAIN.LOCAL\someuser;krb5conffile=/etc/krb5.conf;krbcache=/tmp/SomeNameCachedCreds"`

Following does not work - missing parameter:atleast krbcache or keytab is required
`authenticator=krb5;server=someserver;database=DWH;user id=someuser;password=somepassword;realm=SOMEDOMAIN.LOCAL;krb5conffile=/etc/krb5.conf;"`
I do not have keytab file so I did not test 3rd kind of connection string

Error provider krb5 not found means that krb5 Integrated authorization is not initialized
To initialize it you need to call some functions inside e.g.
I do not like that, but it works (some register function will be more nice)
```
import (
  ia "github.com/microsoft/go-mssqldb/integratedauth/krb5"
)
func main() {
   if ia.AuthProviderFunc == nil {
    fmt.Printf("Kerberos AuthProviderFunc is not set: %v\n", ia.AuthProviderFunc)
}
```
.....

This will initialize krb5 auth provider. It will be better to have some Register function which can be called

**Comment by PeteBassettBet365** [comment]
Hi all. 

Heres the PR https://github.com/microsoft/go-mssqldb/pull/65 

Please note the connection string parameter naming convention. It differs from the previous implementation.

Please give it a test and let me know how you go. If there are issues I can jump on.

Thanks

**Comment by grrlgeek** [comment]
@shueybubbles You merged the PR on March 13; can this Issue be closed?
