### ISSUE TITLE
Bad placeholder counting with insert statement

### ISSUE THREAD

**Issue by nathan-sizemore-kr** [microsoft/go-mssqldb#63]
A valid insert statement requiring zero placeholder values is getting rejected due to `want = ds.si.NumInput()` saying there should be 1 input.

```sql
CREATE TABLE [foo].[blocks]
(
    [id]    UNIQUEIDENTIFIER NOT NULL,
    [geoid] CHAR(12) NOT NULL,
    [block] GEOGRAPHY NOT NULL,

    CONSTRAINT [pk_blocks] PRIMARY KEY CLUSTERED (id ASC),
    CONSTRAINT [unq_bgeo] UNIQUE (geoid)
);
```

```go
conn, err := sql.Open("mssql", connString)
conn.Exec("INSERT INTO [foo].[blocks] (id, geoid, [block]) VALUES('16a2c7de-162c-4557-9694-c249be49b4cd', 'oXRztaWFVAvD', geography::STPolyFromText('POLYGON((-85.204636 32.875304, -85.204636 32.860315, -85.185062 32.860315, -85.185062 32.875304, -85.204636 32.875304))', 4326))")
```

```
2022/10/31 11:01:31 sql: expected 1 arguments, got 0
```

`v1.19.2`
`src/database/sql/convert.go L119`
```go
want = ds.si.NumInput() // reports as wanting 1 arg for a placeholder that doesn't exist
```

**Expected behavior**
The driver should report -1 or the counting bug should be fixed for `geography::XX` functions in statements.

### Further technical details
SQL Server version: SQL Server 2022
Operating system: macOS (Docker container)

**Comment by nathan-sizemore-kr** [comment]
Looks like the `::` gets converted to `:@` during the statement build
![Screen Shot 2022-10-31 at 12 15 00 PM](https://user-images.githubusercontent.com/65302970/199056546-8b3aa7a7-4c61-419c-ad1f-e4854fda3c32.png)

**Comment by shueybubbles** [comment]
Are you using `sqlserver` or `mssql` as the driver name? 
The `:` syntax for placeholders is deprecated per https://github.com/microsoft/go-mssqldb#deprecated

**Comment by nathan-sizemore-kr** [comment]
I wasn't using that syntax if you look above. The driver is converting the substring of the string literal passed in of `geography::STPolyFromText` to `geography:@STPolyFromText`. 

I switched it from "mssql" driver to "sqlserver" driver and it is working.

**Comment by shueybubbles** [comment]
yes I meant to use `sqlserver` to avoid the driver treating `:` as a variable prefix. 
I should probably remove `mssql` as driver name altogether.
