### ISSUE TITLE
build on linux-arm: go-mssqldb@v0.15.0/tds.go:489:24: cannot convert 0xFFFFFFF8 (untyped int constant 4294967288) to type int

### ISSUE THREAD

**Issue by PapaYofen** [microsoft/go-mssqldb#69]
**Describe the bug**

If you are seeing an exception, include the full exceptions details (message and stack trace).

```
Exception message:
Stack trace:
```

**To Reproduce**
Include a complete code listing that we can run to reproduce the issue.

Partial code listings, or multiple fragments of code, will slow down our response or cause us to push the issue back to you to provide code to reproduce the issue.

**Expected behavior**

### Further technical details
SQL Server version: (e.g. SQL Server 2017)
Operating system: (e.g. Windows 2019, Ubuntu 18.04, macOS 10.13, Docker container)
Table schema

**Additional context**

**Comment by shueybubbles** [comment]
@PapaYofen is this still happening? 
We cross-compile a product that uses this driver for Linux ARM64 using a non-ARM VM, see https://github.com/microsoft/go-sqlcmd/blob/403f8eb8cb7eae18014f44ad4a841ecd0983f505/build/azure-pipelines/build-product.yml#L39

Have you tried cross-compiling your app for ARM on a different non-ARM host? I'm curious if it gets the same error.
