### ISSUE TITLE
Breaking change in v0.18.0

### ISSUE THREAD

**Issue by enocom** [microsoft/go-mssqldb#73]
The type signature of msdn.Parse changed from returning three values to two values in [this commit](https://github.com/microsoft/go-mssqldb/commit/ba5a4a01858c9783ba0b75456d09d577e23240e7#diff-2c8ad7a8cbc93a80bee6b50de9c427c98c6aaa7085c16ccf7b01227fdd9a3863R114).

Was this intentional?

**Comment by shueybubbles** [comment]
yes @PeteBassettBet365 moved the parameters to be part of the returned config structure.

**Comment by enocom** [comment]
Got it. Thanks.
