### ISSUE TITLE
prelogin fields data structure breaks when using access token for federated auth with AWS RDS Proxy MS SQL support

### ISSUE THREAD

**Issue by mattgillard** [microsoft/go-mssqldb#84]
**Describe the bug**
1. When i use connection string:

`odbc:server=%s;password={%s};port=%d;fedauth=ActiveDirectoryServicePrincipalAccessToken;`
A valid token as passed as the password, and an AWS RDS MS SQL Proxy configured as the server, I get this error:

`2023/01/29 12:16:08 Error preparing SQL statement:federated authentication is not supported by the server`

2. Below extract from the TDS spec v33 found [here](https://learn.microsoft.com/en-us/openspecs/windows_protocols/ms-tds/b46a581a-39de-4745-b076-ec4dbb7d13ec):
<img width="844" alt="CleanShot 2023-01-30 at 11 59 58@2x" src="https://user-images.githubusercontent.com/6270663/215367184-7712c3fe-8c4a-440c-b486-4233e071de5c.png">
Says that If the server received preloginFEDAUTHREQUIRED - it MUST respond as above.

3. In the prelogin response, as there is no valid preloginFEDAUTHREQUIRED index (6) the check here passes through to the else statement. (see below for debugger screenshots)

```
else if fe.FedAuthLibrary != FedAuthLibraryReserved {
			return 0, fmt.Errorf("federated authentication is not supported by the server")

```

I worked around this issue by removing the else. I am not sure if this is a problem with this library, or if its an issue with the AWS implementation of the protocol. (see below for example dotnet program which works fine - maybe the dotnet implementation doesn't have a similar check?)

[See diffs for fix](https://github.com/microsoft/go-mssqldb/compare/main...mattgillard:go-mssqldb:main):

Exception message: `2023/01/29 12:16:08 Error preparing SQL statement:federated authentication is not supported by the server`

**To Reproduce**
Include a complete code listing that we can run to reproduce the issue.
See here [for gist](https://gist.github.com/mattgillard/ff124f67c7e16318684c961441fd5aa5)

Instructions as per comment in gist:

1. Create an RDS MS SQL Server (Express is fine for cheapness)
2. Create an RDS Proxy (plug in your requirements)
```
aws rds create-db-proxy \
    --db-proxy-name sqlproxy \
    --engine-family SQLSERVER  \
    --auth Description="MS SQL RDS Proxy",AuthScheme="SECRETS",SecretArn="arn:aws:secretsmanager:ap-southeast-2:1234567890:secret:rdsad5de9b2-a9be-4052-a448-ec5112025942-kyUTPL",IAMAuth="ENABLED",ClientPasswordAuthType="SQL_SERVER_AUTHENTICATION" \
    --role-arn "arn:aws:iam::1234567890:role/service-role/rds-proxy-role-1674792657645"\
    --vpc-subnet-ids "subnet-xxx" "subnet-yyy" \
    --vpc-security-group-ids sg-xxx
```
 3. Register your RDS DB with the proxy:

```
aws rds register-db-proxy-targets \
    --db-proxy-name sqlproxy \
    --db-instance-identifiers "sqlexpress"

```

 4. Ensure your IAM User/Role allows `rds-db:connect` as per [AWS IAM docs](https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/UsingWithRDS.IAMDBAuth.IAMPolicy.html)
 5. Enter resulting Proxy FQDN below in server variable
 6. `go run test.go`

**Expected behavior**

I expect the following output (with my patch i get the correct output):

```
$ go run test.go
Connected!
Microsoft SQL Server 2019 (RTM-CU16-GDR) (KB5014353) - 15.0.4236.7 (X64) 
        May 29 2022 15:55:47 
        Copyright (C) 2019 Microsoft Corporation
        Express Edition (64-bit) on Windows Server 2016 Datacenter 10.0 <X64> (Build 14393: ) (Hypervisor)
```

Instead I get this output (without my patch):

```
$ go run query.go
Connected!
2023/01/29 12:04:02 Error preparing SQL statement:federated authentication is not supported by the server
exit status 1
```

### Further technical details
SQL Server version: Any (SQL 2019 Express)
Operating system: Any (MacOS Ventura 13.1 M1)

**Additional context**

prelogin definitions are here:
https://github.com/microsoft/go-mssqldb/blob/main/tds.go#L104

.NET 6 works just fine with Microsoft.Data.SqlClient which implies to me its not an issue with the implementation of the protocol.
Working .NET code [here](https://gist.github.com/mattgillard/f63debb281c9eb26488ea788a5893090).

Debugger screenshot prior to readPrelogin response:

![CleanShot 2023-01-31 at 11 27 22@2x](https://user-images.githubusercontent.com/6270663/215627680-5dc1ad0b-4a52-485d-afe0-f6bf02175517.png)

And after readPrelogin (no key for preloginFEDAUTHREQUIRED):

<img width="719" alt="CleanShot 2023-01-31 at 11 30 01@2x" src="https://user-images.githubusercontent.com/6270663/215627782-582dba4a-6203-4408-8ac3-eeb595e999fc.png">

**Comment by mattgillard** [comment]
Update: After looking at the dotnet SqlClient code - it makes sense why it works - the implementation logic is different for prelogin response.

I am guessing the switch statement never hits `case (int)PreLoginOptions.FEDAUTHREQUIRED` as that option is not returned. So technically Microsoft.Data.SqlClient is breaking the specification.

https://github.com/dotnet/SqlClient/blob/20d4c199923c9b4ea2ffd44d9304fcb306c5efb5/src/Microsoft.Data.SqlClient/netcore/src/Microsoft/Data/SqlClient/TdsParser.cs#L1054

**Comment by shueybubbles** [comment]
I think your scenario doesn't need to use the `azuread` package. There's a fedauth connector you can leverage that doesn't take any dependency on MSAL SDK for Go.  Have you tried using `NewSecurityTokenConnector` directly?

The azuread package sets the fedauth library here https://github.com/microsoft/go-mssqldb/blob/1576f3e37b205df10f9531e75021d1f23a75232a/azuread/configuration.go#L132

Perhaps it should leave it as `FedAuthLibraryReserved`?

**Comment by mattgillard** [comment]
sure - but I get the same problem - as I have to use the azuread driver for federation - I do not see any other option?
As soon as it sees `fedauth` in the connection string - it resets `p.fedAuthLibrary` from the default of mssql.FedAuthLibraryReserved as per:

https://github.com/microsoft/go-mssqldb/blob/1576f3e37b205df10f9531e75021d1f23a75232a/azuread/configuration.go#L81

I tried this:

```
connString := fmt.Sprintf("odbc:server=%s;port=%d;fedauth=FedAuthLibraryReserved;",
		server, port)
	//print(authToken)

	//conn, err := sql.Open(azuread.DriverName, connString)
	tokenProviderWithCtx := func(ctx context.Context) (string, error) {
		return authToken, nil
	}

	connector, err := mssql.NewConnectorWithAccessTokenProvider(connString, tokenProviderWithCtx)
	conn := sql.OpenDB(connector)
```

Maybe we need an extra `fedauth` option for non AAD federation which keeps p.fedAuthLibrary as default. But that would seem messy I guess as all the federation code is in the `azuread` package.

Technically it doesn't matter who is the token provider, `azuread` does the job except for this issue.

**Comment by mattgillard** [comment]
I get it now. Leave it with me and I will find some time to try it. Thanks for the pointer!

**Comment by mattgillard** [comment]
How about this.

```
else if fe.FedAuthLibrary != FedAuthLibraryReserved && fe.ADALWorkflow > 0 {
		return 0, fmt.Errorf("federated authentication is not supported by the server")
	}
```

`NewSecurityTokenConnector` does not set the ADALWorkflow.  I think you only care about the above error message if its actually going through the ADALWorkflow somehow and didn't get the `preloginFEDAUTHREQUIRED` response?

For a generic access token provided by the user the above should be enough as they just want to auth and we don't want to check for the support.

**Comment by shueybubbles** [comment]
sounds good to me! Thx for working it out. Now I need some other curious-and-motivated community members to add Always Encrypted support.
