### ISSUE TITLE
nested result sets fail when executed in a transaction

### ISSUE THREAD

**Issue by miguelsandro** [microsoft/go-mssqldb#95]
```
Exception message: Invalid TDS stream: EOF or unknown token type returned
```
The problem is that when two or more nested result sets are used within an active transaction, the commented error occurs. If we do the same but without being in a transaction, the problem does not appear

### Further technical details
SQL Server version: SQL Server 2016
Operating system: Windows Server 2019

**Comment by shueybubbles** [comment]
@miguelsandro  thx for the issue. Can you please provide a code sample to reproduce the issue?

**Comment by miguelsandro** [comment]
Yes, I'm executing one query with tx.Query then inside the Rows.Next() iteration block I'm making one o more calls to tx.Query.

**Comment by shueybubbles** [comment]
I don't think that's a supported scenario until someone implements MARS on the driver. You'll need to fetch all the rows from the first query then iterate through the data to run the next query.

**Comment by miguelsandro** [comment]
Thanks for the feedback. I will have to modify the code to adapt it to Go
