### ISSUE TITLE
Unable to connect to a default SQLExpress Instance using Shared Memory

### ISSUE THREAD

**Issue by upsampled** [microsoft/go-mssqldb#96]
**Summary**
I am trying to connect to a default SQL Express installation in SQL Auth mode with only the Shared Memory interface available. To do this I am trying to follow the readme instructions:

>To force a specific protocol for the connection there two several options:
>* Prepend the server name in a DSN with the protocol and a colon, like np:host or lpc:host or tcp:host
>* Set the protocol parameter to the protocol name

Following these instruction in the `msdn.Config` and manually results in the following connections string:

```
"sqlserver://sa:password@lpc:DESKTOP-XXXXXXX/MSSQLSERVER01?protocol=lpc"
```
When fed into `mssql.NewConnector` I get the following error:

```
parse "sqlserver://sa:password@lpc:DESKTOP-XXXXXXX/MSSQLSERVER01?protocol=lpc": invalid port ":DESKTOP-XXXXXXX" after host
```

**version**
get command: `go get github.com/microsoft/go-mssqldb@main`
go mod entry: `github.com/microsoft/go-mssqldb v0.20.1-0.20230228011515-c375dfd444dd // indirect`

**Expected behavior**
Connect via shared memory to SQL instance

### Further technical details
SQL Server version: SQL Express 2022
Operating system: Windows 11

**Comment by shueybubbles** [comment]
did you include the sharedmemory package?

```go
import (
_ "github.com/microsoft/go-mssqldb/sharedmemory"
)
```

**Comment by upsampled** [comment]
@shueybubbles, I definitely missed the silent import. This allows for shared memory to work but only when the second rule is applied:

```
sqlserver://sa:password@DESKTOP-XXXXX/MSSQLSERVER01?protocol=lpc
```
the `lpc:` before the hostname still fails
```
parse "sqlserver://sa:password@lpc:DESKTOP-XXXX/MSSQLSERVER01?dial+timeout=0&disableRetry=false&protocol=lpc": invalid port ":DESKTOP-XXXXX" after host
```
Also any insight on how just try shared memory first? The documentation makes it seem like `msdsn.ProtocolParsers`  can be set for this.

**Comment by shueybubbles** [comment]
for a URL DSN, just use the protocol parameter. There's no good way to encode the protocol with the colon as part of the host name. I'm sorry the doc isn't explicit on that. You can use `lpc:` for ODBC- or ADO-style DSNs and omit the protocol parameter.

You can see how sqlcmd forces protocol ordering at https://github.com/microsoft/go-sqlcmd/blob/21afc1f3e140bf4e3fb78fcd9ccb045a2c0edf36/pkg/sqlcmd/sqlcmd_windows_amd64.go#L10

**Comment by upsampled** [comment]
sounds good,

For those looking for how to connect to an MS SQL db via shared memory here is what is working for me:


```
import (
...
_ "github.com/microsoft/go-mssqldb/sharedmemory"
_ "github.com/microsoft/go-mssqldb/namedpipe" //good to include this as well if named pipes might be supported
)

c := &msdsn.Config{
    Host:     host,
    Instance: inst,
    User:     user,
    Password: pass,
    Parameters: make(map[string]string),
}
c.Parameters["protocol"] = "lpc"

conn, err := mssql.NewConnector(c.URL().String())
...
db := sql.OpenDB(conn)
``` 

If you do not want to the connector to behave like the `sqlcmd` and try shared memory, named pipe and finally tcp, then instead do the following

```
import (
...
_ "github.com/microsoft/go-mssqldb/sharedmemory"
_ "github.com/microsoft/go-mssqldb/namedpipe" 
)
//taken from go-sqlcmd
var tcp = msdsn.ProtocolParsers[0]
msdsn.ProtocolParsers[0] = msdsn.ProtocolParsers[2]
msdsn.ProtocolParsers[2] = msdsn.ProtocolParsers[1]
msdsn.ProtocolParsers[1] = tcp

c := &msdsn.Config{
    Host:     host,
    Instance: inst,
    User:     user,
    Password: pass,
    Parameters: make(map[string]string),
}

conn, err := mssql.NewConnector(c.URL().String())
...
db := sql.OpenDB(conn)
``` 
```
